@startuml
set namespaceSeparator none
hide empty members
hide empty methods

class TYPO3.CMS.Core.Tests.Unit.Database.DatabaseConnection {
	+setup()
	+tearDown()
	+selectDbReturnsTrue()
	+selectDbReturnsFalse()
	+sqlAffectedRowsReturnsCorrectAmountOfRows()
	+sqlInsertIdReturnsCorrectId()
	+noSqlError()
	+sqlErrorWhenInsertIntoInexistentField()
	+noSqlErrorCode()
	+sqlErrorNoWhenInsertIntoInexistentField()
	+sqlPconnectReturnsInstanceOfMySqli()
	+connectDbThrowsExeptionsWhenNoDatabaseIsGiven()
	+connectDbConnectsToDatabaseWithoutErrors()
	+fullQuoteStrReturnsQuotedStringDataProvider()
	+fullQuoteStrReturnsQuotedString()
	+fullQuoteArrayQuotesArrayDataProvider()
	+fullQuoteArrayQuotesArray()
	+quoteStrQuotesCorrectlyDataProvider()
	+quoteStrQuotesDoubleQuotesCorrectly()
	+cleanIntArrayReturnsCleanedArrayDataProvider()
	+cleanIntArrayReturnsCleanedArray()
	+cleanIntListReturnsCleanedString()
	+cleanIntListReturnsCleanedString()
	+disconnectIfConnectedDisconnects()
	+adminQueryReturnsTrueForInsertQuery()
	+adminQueryReturnsTrueForUpdateQuery()
	+adminQueryReturnsTrueForDeleteQuery()
	+adminQueryReturnsResultForSelectQuery()
	+adminGetCharsetsReturnsArrayWithCharsets()
	+adminGetKeysReturnIndexKeysOfTable()
	+adminGetFieldsReturnFieldInformationsForTable()
	+adminGetTablesReturnAllTablesFromDatabase()
	+adminGetDbsReturnsAllDatabases()
	+insertQueryCreateValidQuery()
	+insertQueryCreateValidQueryFromMultipleValues()
	+insertMultipleRowsCreateValidQuery()
	+updateQueryCreateValidQuery()
	+deleteQueryCreateValidQuery()
	+selectQueryCreateValidQuery()
	+selectQueryCreateValidQueryWithEmptyWhereClause()
	+selectQueryCreateValidQueryWithGroupByClause()
	+selectQueryCreateValidQueryWithOrderByClause()
	+selectQueryCreateValidQueryWithLimitClause()
	+selectSubQueryCreateValidQuery()
	+truncateQueryCreateValidQuery()
	+prepareSelectQueryCreateValidQuery()
	+sqlNumRowsReturnsCorrectAmountOfRowsProvider()
	+sqlNumRowsReturnsCorrectAmountOfRows()
	+sqlNumRowsReturnsFalse()
	+prepareTableForFetchTests()
	+sqlFetchAssocReturnsAssocArray()
	+sqlFetchRowReturnsNumericArray()
	+sqlFreeResultReturnsFalse()
	+sqlFreeResultReturnsNull()
	+sql_select_dbReturnsTrue()
	+sql_select_dbReturnsFalse()
	+storedFullAsciiRangeCallsLinkObjectWithGivenData()
	+storedGzipCompressedDataReturnsSameData()
	+listQueryWithIntegerCommaAsValue()
	+listQueryThrowsExceptionIfValueContainsComma()
	+searchQueryDataProvider()
	+searchQueryCreatesQuery()
	+escapeStringForLikeComparison()
	+stripOrderByForOrderByKeywordDataProvider()
	+stripOrderByForOrderByKeyword()
	+stripGroupByForGroupByKeywordDataProvider()
	+stripGroupByForGroupByKeyword()
	+cleanIntArrayDataProvider()
	+cleanIntArray()
}
@enduml
