@startuml
set namespaceSeparator none
hide empty members
hide empty methods

class TYPO3.CMS.Core.Database.DatabaseConnection {
	+admin_get_dbs(): array
	+admin_get_tables(): array
	+admin_get_fields($tableName): array
	+admin_get_keys($tableName): array
	+admin_get_charsets(): array
	+admin_query($query): mysqli_result object
}
@enduml
