@startuml
set namespaceSeparator none
hide empty members
hide empty methods

interface Doctrine.DBAL.Driver.Connection

class Docrine.DBAL.Connection implements Doctrine.DBAL.Driver.Connection {
  #Doctrine.DBAL.Driver.Connection $_conn
}
@enduml
